---
# Homepage configuration
# See https://fontawesome.com/search for icons options

title: "比特彗星资源导航页"
subtitle: "Bitcomet"
logo: "/assets/icons/bitcomet-x256.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: '<p>本页面由使用比特彗星的爱好者创建与比特彗星官方无关 <br> Powered by <a href="https://github.com/bastienwirtz/homer">Homer</a> &amp; <a href="https://pages.cloudflare.com/">Cloudflare Pages</a></p>' # set false if you want to hide it.

# Set the default layout and color scheme
defaults:
  layout: list # Either 'columns', or 'list'
  colorTheme: auto # One of 'auto', 'light', or 'dark'

# Optional theme customization
theme: default

# Optional theme customization (color overrrides)
# overrrides can also be done using CSS vars 
colors:
  light:
    highlight-primary: "#ffa500"
    highlight-secondary: "#e1ebf5"
    highlight-hover: "#8cacbb"
    background: "#f0f0f0"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#000000"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#A36A00"
    highlight-secondary: "#284F77"
    highlight-hover: "#3E7CBA"
    background: "#2B2B2B"
    card-background: "#3B3B3B"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "GitHub后端"
    icon: "fab fa-github"
    url: "https://github.com/bitcomet-post-bar/bc-navigation"
    target: "_blank"
  - name: "比特彗星历史版本备份"
    icon: "fa-solid fa-clock"
    url: "/legacy"
    target: "_blank"
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  #- name: "another page!"
  #  icon: "fas fa-file-alt"
  #  url: "#additional-page" 

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "官方链接"
    icon: "fa-solid fa-meteor"
    items:
      - name: "官方主页"
        logo: "/assets/icons/bitcomet-logo.svg"
        subtitle: "比特彗星官方主页"
        url: "https://www.bitcomet.com/cn"
        target: "_blank"
      - name: "彗星论坛"
        icon: "fa-brands fa-discourse"
        subtitle: "比特彗星中文论坛"
        url: "https://www.cometbbs.com/"
        target: "_blank"
      - name: "官方Wiki（中文）"
        logo: "/assets/icons/wikipedia.svg"
        subtitle: "比特彗星官方维基（中文）"
        url: "http://wiki-zh.bitcomet.com/"
        target: "_blank"
      - name: "官方Wiki（英文）"
        logo: "/assets/icons/wikipedia.svg"
        subtitle: "比特彗星官方维基（英文）"
        url: "http://wiki.bitcomet.com/"
        target: "_blank"
      - name: "安卓版"
        logo: "/assets/icons/android-2.svg"
        subtitle: "下载比特彗星安卓版"
        url: "https://www.bitcomet.com/cn/android"
        target: "_blank"
      - name: "MacOS版"
        logo: "/assets/icons/macos.svg"
        subtitle: "下载比特彗星MacOS版"
        url: "https://www.bitcomet.com/cn/downloads#mac"
        target: "_blank"
      - name: "Linux版"
        logo: "/assets/icons/Linux.svg"
        subtitle: "下载比特彗星Linux版"
        url: "https://wiki-zh.bitcomet.com/linux%E7%89%88bitcomet%E5%AE%89%E8%A3%85%E6%8C%87%E5%8D%97#linux_%E7%89%88_bitcomet_%E5%AE%89%E8%A3%85%E6%8C%87%E5%8D%97"
        target: "_blank"
      - name: "Docker版（GUI）"
        logo: "/assets/icons/docker.svg"
        subtitle: "图形界面模式的 BitComet Docker"
        url: "https://wiki-zh.bitcomet.com/linux%E7%89%88bitcomet%E5%AE%89%E8%A3%85%E6%8C%87%E5%8D%97#docker_%E9%95%9C%E5%83%8F_gui%E5%9B%BE%E5%BD%A2%E7%95%8C%E9%9D%A2%E6%A8%A1%E5%BC%8F"
        target: "_blank"
      - name: "Docker版（WebUI）"
        logo: "/assets/icons/docker.svg"
        subtitle: "WebUI界面模式的 BitComet Docker"
        url: "https://wiki-zh.bitcomet.com/linux%E7%89%88bitcomet%E5%AE%89%E8%A3%85%E6%8C%87%E5%8D%97#docker_%E9%95%9C%E5%83%8F_webui%E7%95%8C%E9%9D%A2%E6%A8%A1%E5%BC%8F"
        target: "_blank"
  - name: "教程和帮助"
    icon: "fa-solid fa-circle-question"
    items:
      - name: "BC常见问题"
        logo: "/assets/icons/bilibili.svg"
        subtitle: "解决比特彗星使用过程中遇到的常见问题"
        url: "https://www.bilibili.com/read/readlist/rl739074"
        target: "_blank"
      - name: "BC端口阻塞解决方案"
        logo: "/assets/icons/bilibili.svg"
        subtitle: "解决比特彗星 端口阻塞问题"
        url: "https://www.bilibili.com/read/readlist/rl683227"
        target: "_blank"
      - name: "LCUKY系列教程"
        logo: "/assets/icons/lucky.svg"
        subtitle: "使用lucky实现STUN穿透和反向代理"
        url: "https://www.bilibili.com/read/readlist/rl772361"
        target: "_blank"
      - name: "比特彗星吧"
        logo: "/assets/icons/baidu-color.svg"
        subtitle: ""
        url: "https://tieba.baidu.com/f?kw=%B1%C8%CC%D8%E5%E7%D0%C7"
        target: "_blank"
      - name: "比特彗星贴吧解锁版"
        logo: "/assets/icons/icon_tools.svg"
        subtitle: ""
        url: "https://github.com/bitcomet-post-bar/BC-modified"
        target: "_blank"
      - name: "BTN IP List 镜像"
        icon: "fa-solid fa-filter"
        subtitle: ""
        url: "https://github.com/bitcomet-post-bar/BTN-IP-LIST"
        target: "_blank"
      - name: "Tracker List 镜像"
        icon: "fa-solid fa-server"
        subtitle: ""
        url: "https://github.com/bitcomet-post-bar/XIU2sTrackersList"
        target: "_blank"
      - name: "客户端过滤规则"
        icon: "fa-solid fa-network-wired"
        subtitle: ""
        url: "https://github.com/bitcomet-post-bar/BC-Client-Filter"
        target: "_blank"
  - name: "综合BT站点"
    icon: "fa-solid fa-file"
    items:
      - name: "Torrent Galaxy"
        logo: "/assets/icons/tgx.jpg"
        subtitle: "重建后的TGX"
        url: "https://torrentgalaxy.one/"
        target: "_blank"
      - name: "1337X"
        logo: "/assets/icons/1337x.svg"
        subtitle: ""
        url: "https://1337x.to/"
        target: "_blank"
      - name: "The RARBG"
        logo: "/assets/icons/RARBG.png"
        subtitle: "重建后的RARBG"
        url: "https://therarbg.com/"
        target: "_blank"
      - name: "EZTV"
        logo: "/assets/icons/eztv.png"
        subtitle: ""
        url: "https://eztvx.to/home"
        target: "_blank"
      - name: "BT之家"
        logo: "/assets/icons/bt之家.png"
        subtitle: ""
        url: "https://www.1lou.cc/"
        target: "_blank"
      - name: "海盗湾"
        logo: "/assets/icons/the-pirate-bay.svg"
        subtitle: "The Pirate Bay"
        url: "https://thepiratebay.org/index.html"
        target: "_blank"
  - name: "磁力搜索引擎"
    icon: "fa-solid fa-magnet"
    items:
      - name: "BT4G"
        logo: "/assets/icons/bt4g.png"
        subtitle: ""
        url: "https://bt4gprx.com/"
        target: "_blank"
      - name: "BTDig"
        logo: "/assets/icons/btdig.png"
        subtitle: ""
        url: "https://btdig.com/index.htm"
        target: "_blank"
      - name: "BTSOW"
        logo: "/assets/icons/btsow.png"
        subtitle: ""
        url: "https://tellme.pw/btsow"
        target: "_blank"
      - name: "SkrBT"
        logo: "/assets/icons/skrbt.png"
        subtitle: ""
        url: "https://soskr.net/"
        target: "_blank"
      - name: "磁力猫"
        logo: "/assets/icons/磁力猫.png"
        subtitle: ""
        url: "https://xn--a-2h9a4sv66g.com/"
        target: "_blank"
  - name: "实用工具"
    icon: "fa-solid fa-wrench"
    items:
      - name: "字幕库"
        logo: "/assets/icons/字幕库.png"
        subtitle: ""
        url: "https://srtku.com/"
        target: "_blank"
      - name: "What's the Link?"
        logo: "/assets/icons/whats_the_link.ico"
        subtitle: "磁链截图预览"
        url: "https://whatslink.info/"
        target: "_blank"
      - name: "btcache"
        logo: "/assets/icons/database.png"
        subtitle: "磁力和种子文件转换"
        url: "https://btcache.me/"
        target: "_blank"
      - name: "iTorrents"
        logo: "/assets/icons/itorrents.ico"
        subtitle: "磁力和种子文件转换"
        url: "https://itorrents.org/"
        target: "_blank"
      - name: "I know what you download"
        logo: "/assets/icons/ban-utorrent.png"
        subtitle: ""
        url: "https://iknowwhatyoudownload.com/en/peer/"
        target: "_blank"
      - name: "TCP port checker"
        icon: "fa-solid fa-ethernet"
        subtitle: "在线TCP端口扫描工具"
        url: "https://zh.infobyip.com/tcpportchecker.php"
        target: "_blank"
  - name: "动漫站点"
    icon: "fa-solid fa-circle-play"
    items:
      - name: "末日动漫资源库"
        logo: "/assets/icons/末日动漫.ico"
        subtitle: ""
        url: "https://share.acgnx.se/"
        target: "_blank"
      - name: "VCB-Studio"
        logo: "/assets/icons/vcb.png"
        subtitle: ""
        url: "https://vcb-s.com/"
        target: "_blank"
      - name: "动漫花园"
        logo: "/assets/icons/动漫花园.ico"
        subtitle: ""
        url: "https://share.dmhy.org/"
        target: "_blank"
      - name: "Nyaa"
        logo: "/assets/icons/nyaa.png"
        subtitle: ""
        url: "https://nyaa.si/"
        target: "_blank"
      - name: "ACG.RIP"
        logo: "/assets/icons/acg.rip.ico"
        subtitle: ""
        url: "https://acg.rip/"
        target: "_blank"
      - name: "恋爱动漫"
        logo: "/assets/icons/爱恋动漫.png"
        subtitle: ""
        url: "https://www.kisssub.org/"
        target: "_blank"
      - name: "萌番组"
        logo: "/assets/icons/萌番组.svg"
        subtitle: ""
        url: "https://bangumi.moe/"
        target: "_blank"